### ISSUE TITLE
Support `scala_macro_library`

### ISSUE THREAD

**Issue by susliko** [ValdemarGr/mezel#36]
Currently the aspect [ignores](https://github.com/ValdemarGr/mezel/blob/c4f8ef172e41a71058ef795dbdf539faf28f4381/aspects/aspect.bzl#L11) [scala_macro_library](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_macro_library.md). Is that intentional, did it cause any problems?

**Comment by ValdemarGr** [comment]
Should be fixed in `0.2.4`, tell me if any more issues occur.

**Comment by susliko** [comment]
Macro libraries appeared in the build target list, thanks!
