### ISSUE TITLE
Should this many build events happen on a single file change?

### ISSUE THREAD

**Issue by susliko** [ValdemarGr/mezel#40]
I'm not sure if it's really an issue, but logs reveal like a lot of actions being done upon a single file change.
Repo is https://github.com/susliko/bazel-cross-scala 
What I do is introduce some error in `core/.../b/B.scala`
Here's what I see dumped to logs in that second: https://gist.github.com/susliko/76239e4522fde7c0073656e286319dd4

These lines look suspicious. Should they be there on every change in any file?

```
2024.09.02 19:34:57 INFO  started task: 17: buildTarget/scalaMainClasses: starting fiber 17, awaiting lock
```

```
2024.09.02 19:34:57 INFO  started task: 18: buildTarget/scalaTestClasses: starting fiber 18, awaiting lock
```

```
2024.09.02 19:34:57 WARN  16: buildTarget/compile: no diagnostics file for Label(@//core:a), this will cause a degraded experience
2024.09.02 19:34:57 WARN  16: buildTarget/compile: no diagnostics file for Label(@//core:c), this will cause a degraded experience
```

```
2024.09.02 19:34:57 INFO  started task: 16: buildTarget/compile: Shutting down process
```
What does this shutdown mean?

**Comment by ValdemarGr** [comment]
Metals is sending the `scalaMainClasses` request message to `Mezel`, so I don't think I can answer that well. I think metals occasionally polls the build server.

You can configure your metals client to change this behaviour:
```
-Dmetals.verbose=true
-Dmetals.askToReconnect=false
-Dmetals.loglevel=debug
-Dmetals.build-server-ping-interval=10h
```

Any event looking like `1: build/initialize -> watcher: did build change form looking at the interesting events? false for /home/valde/git/.../Blabla.scala` is mezel noticing a change in the project, and deciding if it should tell metals to refresh the projcet, say if a `BUILD.bazel` files change.

The no diagnostics file line I don't know too much about. It seemed like the `aquery` you ran from the other issue declared outputs which weren't created by `rules_scala`.

The shutting down part is part of a nominal bazel invocation by mezel, the process needs to be cleaned up once it is no longer used.

**Comment by susliko** [comment]
Thanks!
